import Head from "next/head";
import * as React from 'react';
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const water = [
    "vit",
    "vurra",
    "sigha",
    "aura",
    "chang",
    "sprinkle",
    "crystal",
    "aquafinas",
    "contresax",
    "sta maria",
    "pura",
    "kerry",
  ];
  const output = [];
  const one = [];
  function loop3() {
    water.sort();
    for (var i = 0; i < water.length; i++) {
      if (one.indexOf(water[i].substring(1, 0)) < 0) {
        one.push(water[i].substring(1, 0));
        let aa = water.filter(
          (big) => big.substring(1, 0) == water[i].substring(1, 0)
        );
        output.push({ letter: water[i].substring(1, 0), list: aa });
      } else {
      }
    }
    console.log("true", one);
    console.log("out", output);
    const string = JSON.stringify(output, null, 4);
    document.querySelector(".output").innerHTML = string;
  }
  React.useEffect(() => {
    loop3();
  }, []);
  return (
    <>
      <Head>
        <title>solved & implement</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <pre class="output"></pre>
    </>
  );
}
